/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AboutTeam.java
 *
 * Created on 14/05/2011, 13:12:09
 */
package components;

/**
 *
 * @author Sisi
 */
public class AboutTeam extends javax.swing.JFrame {

    /** Creates new form AboutTeam */
    public AboutTeam() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentPanel = new javax.swing.JPanel();
        studentName = new javax.swing.JLabel();
        uff = new javax.swing.JLabel();
        professorPanel = new javax.swing.JPanel();
        professorName = new javax.swing.JLabel();
        university = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About Team");

        studentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Student"));
        studentPanel.setName("studentPanel"); // NOI18N

        studentName.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        studentName.setText("Fernanda Floriano Silva");
        studentName.setName("studentName"); // NOI18N

        uff.setText("Fluminense Federal University (UFF). ");
        uff.setName("uff"); // NOI18N

        org.jdesktop.layout.GroupLayout studentPanelLayout = new org.jdesktop.layout.GroupLayout(studentPanel);
        studentPanel.setLayout(studentPanelLayout);
        studentPanelLayout.setHorizontalGroup(
            studentPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(studentName)
            .add(uff)
        );
        studentPanelLayout.setVerticalGroup(
            studentPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(studentPanelLayout.createSequentialGroup()
                .add(studentName)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(uff)
                .addContainerGap(6, Short.MAX_VALUE))
        );

        professorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Professor"));
        professorPanel.setName("professorPanel"); // NOI18N

        professorName.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        professorName.setText("Leonardo Gresta Paulino Murta");
        professorName.setName("professorName"); // NOI18N

        university.setText("Assistant Professor, IC/UFF ");
        university.setName("university"); // NOI18N

        org.jdesktop.layout.GroupLayout professorPanelLayout = new org.jdesktop.layout.GroupLayout(professorPanel);
        professorPanel.setLayout(professorPanelLayout);
        professorPanelLayout.setHorizontalGroup(
            professorPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(professorPanelLayout.createSequentialGroup()
                .add(professorPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(professorName)
                    .add(university))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        professorPanelLayout.setVerticalGroup(
            professorPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(professorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(professorName)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(university)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/components/icons/timeMenu.png"))); // NOI18N
        image.setName("image"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(image)
                    .add(studentPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(professorPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(image)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(studentPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(professorPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AboutTeam().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JLabel professorName;
    private javax.swing.JPanel professorPanel;
    private javax.swing.JLabel studentName;
    private javax.swing.JPanel studentPanel;
    private javax.swing.JLabel uff;
    private javax.swing.JLabel university;
    // End of variables declaration//GEN-END:variables
}
