/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GenericError.java
 *
 * Created on 19/05/2011, 07:59:42
 */
package components;

/**
 *
 * @author Fernanda Floriano Silva
 */
public class GenericError extends javax.swing.JDialog {

    /** Creates new form GenericError */
    public GenericError(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        errorMsgLabel = new javax.swing.JLabel();
        msgError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Error");

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(GenericError.class);
        icon.setIcon(resourceMap.getIcon("icon.icon")); // NOI18N
        icon.setDisabledIcon(null);
        icon.setName("icon"); // NOI18N

        errorLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        errorLabel.setText("Error");
        errorLabel.setName("errorLabel"); // NOI18N

        errorMsgLabel.setText("Error Message:");
        errorMsgLabel.setName("errorMsgLabel"); // NOI18N

        msgError.setText("...");
        msgError.setName("msgError"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(icon)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(errorMsgLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(msgError))
                    .add(errorLabel))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(icon)
                    .add(layout.createSequentialGroup()
                        .add(errorLabel)
                        .add(12, 12, 12)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(errorMsgLabel)
                            .add(msgError))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                GenericError dialog = new GenericError(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel errorMsgLabel;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel msgError;
    // End of variables declaration//GEN-END:variables
}
