/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainDiff.java
 *
 * Created on 24/05/2011, 07:42:34
 */
package components;

import javax.swing.ImageIcon;
import org.jdesktop.application.Action;

/**
 *
 * @author Fernanda Floriano Silva
 */
public class MainDiff extends javax.swing.JFrame {

    /** Creates new form MainDiff */
    public MainDiff() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon("src/main/resources/components/icons/icon.png").getImage());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        uff = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        granularityLabel = new javax.swing.JLabel();
        run = new javax.swing.JButton();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DIFF -ILCS");

        uff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/components/icons/uff.jpg"))); // NOI18N
        uff.setName("uff"); // NOI18N

        nameLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        nameLabel.setText("ILCS - Differences and moves");
        nameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nameLabel.setName("nameLabel"); // NOI18N

        granularityLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        granularityLabel.setText("detection in directories and files");
        granularityLabel.setName("granularityLabel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(MainDiff.class, this);
        run.setAction(actionMap.get("runDiff")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(MainDiff.class);
        run.setIcon(resourceMap.getIcon("run.icon")); // NOI18N
        run.setToolTipText("Start");
        run.setBorder(null);
        run.setBorderPainted(false);
        buttonGroup1.add(run);
        run.setContentAreaFilled(false);
        run.setName("run"); // NOI18N

        close.setAction(actionMap.get("close")); // NOI18N
        close.setIcon(resourceMap.getIcon("close.icon")); // NOI18N
        close.setToolTipText("Close");
        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.setFocusPainted(false);
        close.setName("close"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(uff, 0, 0, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, nameLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, granularityLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(50, 50, 50)
                .add(close, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(run, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(uff, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(nameLabel)
                        .add(12, 12, 12)
                        .add(granularityLabel))
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(run, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(close, 0, 0, Short.MAX_VALUE))))
                .add(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainDiff().setVisible(true);
            }
        });
    }

    @Action
    public void runDiff() {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new FileSelection().setVisible(true);
            }
        });
    }

    @Action
    public void close() {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                System.exit(0);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton close;
    private javax.swing.JLabel granularityLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton run;
    private javax.swing.JLabel uff;
    // End of variables declaration//GEN-END:variables
}
