package components;

/**
 *
 * @author Fernanda Floriano Silva
 */
public class MainDiff extends javax.swing.JFrame {

    /** Creates new form MainDiff */
    public MainDiff() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressDialog = new javax.swing.JDialog();
        icon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        cancel = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        upPanel = new javax.swing.JPanel();
        mainLabel = new javax.swing.JLabel();
        artifact1TextField = new javax.swing.JTextField();
        artifact1 = new javax.swing.JLabel();
        artifact2TextField = new javax.swing.JTextField();
        artifact2 = new javax.swing.JLabel();
        open1 = new javax.swing.JLabel();
        open2 = new javax.swing.JLabel();
        compareWith = new javax.swing.JLabel();
        panelButton = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        progressDialog.setTitle("Progress");
        progressDialog.setName("progressDialog"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(MainDiff.class);
        icon.setIcon(resourceMap.getIcon("icon.icon")); // NOI18N
        icon.setName("icon"); // NOI18N

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12));
        jLabel1.setText("Running");
        jLabel1.setName("jLabel1"); // NOI18N

        jProgressBar1.setName("jProgressBar1"); // NOI18N

        cancel.setIcon(resourceMap.getIcon("cancel.icon")); // NOI18N
        cancel.setToolTipText("Cancel");
        cancel.setBorderPainted(false);
        cancel.setContentAreaFilled(false);
        cancel.setName("cancel"); // NOI18N

        org.jdesktop.layout.GroupLayout progressDialogLayout = new org.jdesktop.layout.GroupLayout(progressDialog.getContentPane());
        progressDialog.getContentPane().setLayout(progressDialogLayout);
        progressDialogLayout.setHorizontalGroup(
            progressDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(progressDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(progressDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(progressDialogLayout.createSequentialGroup()
                        .add(icon)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel1))
                    .add(progressDialogLayout.createSequentialGroup()
                        .add(jProgressBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        progressDialogLayout.setVerticalGroup(
            progressDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(progressDialogLayout.createSequentialGroup()
                .add(progressDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(progressDialogLayout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(jLabel1))
                    .add(progressDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(icon)))
                .add(18, 18, 18)
                .add(progressDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jProgressBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(cancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Differences and moves detector");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(0, 0, 51));
        mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainPanel.setName("mainPanel"); // NOI18N

        upPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        upPanel.setName("upPanel"); // NOI18N

        mainLabel.setFont(new java.awt.Font("sansserif", 1, 14));
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setText("Comparable Artifacts Selection");
        mainLabel.setName("mainLabel"); // NOI18N

        artifact1TextField.setText("Select directory or file...");
        artifact1TextField.setName("artifact1TextField"); // NOI18N

        artifact1.setText("Artifact:");
        artifact1.setName("artifact1"); // NOI18N

        artifact2TextField.setText("Select directory or file...");
        artifact2TextField.setName("artifact2TextField"); // NOI18N

        artifact2.setText("Artifact:");
        artifact2.setName("artifact2"); // NOI18N

        open1.setIcon(resourceMap.getIcon("open1.icon")); // NOI18N
        open1.setName("open1"); // NOI18N

        open2.setIcon(resourceMap.getIcon("open2.icon")); // NOI18N
        open2.setName("open2"); // NOI18N

        compareWith.setFont(new java.awt.Font("sansserif", 1, 12));
        compareWith.setText("Compare with:");
        compareWith.setName("compareWith"); // NOI18N

        org.jdesktop.layout.GroupLayout upPanelLayout = new org.jdesktop.layout.GroupLayout(upPanel);
        upPanel.setLayout(upPanelLayout);
        upPanelLayout.setHorizontalGroup(
            upPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(upPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(mainLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
            .add(upPanelLayout.createSequentialGroup()
                .add(18, 18, 18)
                .add(upPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(upPanelLayout.createSequentialGroup()
                        .add(compareWith)
                        .addContainerGap())
                    .add(upPanelLayout.createSequentialGroup()
                        .add(artifact1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(artifact2TextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(open1)
                        .add(17, 17, 17))))
            .add(upPanelLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(artifact2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(artifact1TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 337, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(open2)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        upPanelLayout.setVerticalGroup(
            upPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(upPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(mainLabel)
                .add(12, 12, 12)
                .add(upPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(upPanelLayout.createSequentialGroup()
                        .add(open1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(upPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(upPanelLayout.createSequentialGroup()
                                .add(8, 8, 8)
                                .add(compareWith)
                                .add(18, 18, 18)
                                .add(upPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(artifact2)
                                    .add(artifact1TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, open2)))
                    .add(upPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(artifact2TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(artifact1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelButton.setBackground(new java.awt.Color(255, 255, 255));
        panelButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelButton.setName("panelButton"); // NOI18N

        jButton1.setFont(new java.awt.Font("sansserif", 1, 12));
        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText("OK");
        jButton1.setContentAreaFilled(false);
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setFont(new java.awt.Font("sansserif", 1, 12));
        jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setContentAreaFilled(false);
        jButton2.setName("jButton2"); // NOI18N

        org.jdesktop.layout.GroupLayout panelButtonLayout = new org.jdesktop.layout.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .add(jButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 264, Short.MAX_VALUE)
                .add(jButton1)
                .addContainerGap())
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelButtonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jButton1)
                .add(jButton2))
        );

        org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, panelButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, upPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(upPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(186, 186, 186))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 224, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainDiff().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel artifact1;
    private javax.swing.JTextField artifact1TextField;
    private javax.swing.JLabel artifact2;
    private javax.swing.JTextField artifact2TextField;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel compareWith;
    private javax.swing.JLabel icon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel open1;
    private javax.swing.JLabel open2;
    private javax.swing.JPanel panelButton;
    private javax.swing.JDialog progressDialog;
    private javax.swing.JPanel upPanel;
    // End of variables declaration//GEN-END:variables
}
