/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DDiffProgress.java
 *
 * Created on 14/01/2012, 12:18:01
 */
package components;

import diretorioDiff.ProgressMessager;
import java.awt.AlphaComposite;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import sun.net.ProgressMeteringPolicy;

/**
 *
 * @author Eraldo
 */
public class DDiffProgress extends javax.swing.JDialog implements ProgressMessager {

    /** Creates new form DDiffProgress */
    public DDiffProgress(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        setUndecorated(true); 
        initComponents(); 
        setLocationRelativeTo(parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        messageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLayeredPane1.setAlignmentX(0.0F);
        jLayeredPane1.setAlignmentY(0.0F);
        jLayeredPane1.setName("jLayeredPane1"); // NOI18N

        messageLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(255, 255, 255));
        messageLabel.setAlignmentY(0.0F);
        messageLabel.setName("messageLabel"); // NOI18N
        messageLabel.setPreferredSize(new java.awt.Dimension(136, 15));
        messageLabel.setBounds(10, 280, 350, 40);
        jLayeredPane1.add(messageLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/components/icons/logoSplash.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setOpaque(true);
        jLabel1.setBounds(0, 0, 363, 325);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel messageLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setMessage(String message) {
        messageLabel.setText(message);
        messageLabel.setToolTipText(message);
        System.out.println(message);
    }    
}
