package components;

import details.Icon;
import details.Laf;
import diretorioDiff.resultados.ResultadoArquivo;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import wrap.Wrap;
import org.jdesktop.application.Action;

/**
 *
 * @author Fernanda Floriano Silva
 */
@SuppressWarnings("serial")
public class MainFDiff extends javax.swing.JFrame {

    private FileComponent fileComponent = new FileComponent();
    private static MainFDiff instance;

    public synchronized static MainFDiff getInstance(File file, ResultadoArquivo result) {
        if (instance != null) {
            instance.dispose();
        }
        instance = new MainFDiff(file, result);
        return instance;
    }

    public static synchronized void resetInstance() {
        instance = null;
    }

    /** Creates new form FileOverView
     * @param file
     * @param result  
     */
    public MainFDiff(File file, ResultadoArquivo result) {
        initComponents();
        Laf.setlaf();
        setLocationRelativeTo(null);
        setIconImage(Icon.getIcon());

        try {
            init(file);
            showResult(result);
        } catch (MalformedURLException ex) {
            Logger.getLogger(MainFDiff.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainFDiff.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void init(File file) throws MalformedURLException, IOException {
        new Wrap().setWrapPane(pane);
        fileComponent.submitFile(file, pane);
        panel.setBorder(BorderFactory.createTitledBorder(file.getName()));
    }
    /**
     * Show Diff
     */
    @Action
    public void back() {
        this.dispose();
    }

    private void showResult(ResultadoArquivo result) {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pane = new javax.swing.JTextPane();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("File Overview");
        setResizable(false);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("File Name"));
        panel.setMaximumSize(new java.awt.Dimension(717, 619));
        panel.setMinimumSize(new java.awt.Dimension(717, 619));
        panel.setName("panel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        pane.setName("pane"); // NOI18N
        jScrollPane1.setViewportView(pane);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        jSeparator2.setName("jSeparator2"); // NOI18N
        jToolBar1.add(jSeparator2);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(MainFDiff.class, this);
        jButton1.setAction(actionMap.get("back")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(MainFDiff.class);
        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jSeparator1.setName("jSeparator1"); // NOI18N
        jToolBar1.add(jSeparator1);

        jTextField3.setEditable(false);
        jTextField3.setToolTipText("");
        jTextField3.setEnabled(false);
        jTextField3.setFocusable(false);
        jTextField3.setMaximumSize(new java.awt.Dimension(460, 28));
        jTextField3.setMinimumSize(new java.awt.Dimension(460, 28));
        jTextField3.setName("jTextField3"); // NOI18N
        jTextField3.setPreferredSize(new java.awt.Dimension(460, 28));
        jToolBar1.add(jTextField3);

        jTextField1.setBackground(new java.awt.Color(53, 94, 121));
        jTextField1.setEditable(false);
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Refactoring Highlight");
        jTextField1.setMaximumSize(new java.awt.Dimension(127, 28));
        jTextField1.setMinimumSize(new java.awt.Dimension(127, 28));
        jTextField1.setName("jTextField1"); // NOI18N
        jToolBar1.add(jTextField1);

        jTextField2.setBackground(new java.awt.Color(126, 192, 238));
        jTextField2.setEditable(false);
        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setMaximumSize(new java.awt.Dimension(75, 28));
        jTextField2.setMinimumSize(new java.awt.Dimension(75, 28));
        jTextField2.setName("jTextField2"); // NOI18N
        jToolBar1.add(jTextField2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextPane pane;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
