package gui;

import ddiff.ProgressMessager;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public class DDiffProgress extends javax.swing.JDialog implements ProgressMessager {
    private static final long serialVersionUID = 1L;

    /** Creates new form DDiffProgress
     * @param parent
     * @param modal  
     */
    public DDiffProgress(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        setUndecorated(true); 
        initComponents(); 
        setLocationRelativeTo(parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        messageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLayeredPane1.setAlignmentX(0.0F);
        jLayeredPane1.setAlignmentY(0.0F);
        jLayeredPane1.setName("jLayeredPane1"); // NOI18N

        messageLabel.setFont(new java.awt.Font("Tahoma", 0, 10));
        messageLabel.setForeground(new java.awt.Color(255, 255, 255));
        messageLabel.setAlignmentY(0.0F);
        messageLabel.setName("messageLabel"); // NOI18N
        messageLabel.setPreferredSize(new java.awt.Dimension(136, 15));
        messageLabel.setBounds(10, 280, 340, 30);
        jLayeredPane1.add(messageLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/splash.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setOpaque(true);
        jLabel1.setBounds(0, 0, 363, 330);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel messageLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setMessage(String message) {
        DateFormat formato = new SimpleDateFormat("HH:mm:ss.SSS");

        messageLabel.setText(message);
        messageLabel.setToolTipText(message);
        System.out.println(message + formato.format(new Date()));
    }    
}
